# Integrating well logs divided in different files and/or columns

With this code you will be able to integrate DT and RHOB logs in one .las file.

In [1]:
import las
import numpy as np
import sys
import lasio

Copy and paste here the address of your files.

In [2]:
las_files = ('perfis/1RJS_0051__RJ_1RJS_0051__RJ_BHC_00003.las', 'perfis/1RJS_0051__RJ_1RJS_0051__RJ_FDC_CNL_00001.las', 'perfis/1RJS_0051__RJ_1RJS_0051__RJ_FDC_CNL_GR_00004.las', 'perfis/1RJS_0051__RJ_1RJS_0051__RJ_IES_00005.las', 'perfis/1RJS_0051__RJ_1RJS_0051__RJ_ISF_BHC_GR_00002.las', 'perfis/1RJS_0051__RJ_1RJS_0051__RJ_SIGEO__013_00006.las')

In [3]:
N_files = len(las_files)
N_files

6

In [4]:
for i in range(N_files):
    globals()['log%s' % i] = las.LASReader(las_files[i])

In [5]:
log0.step

0.1524

In [6]:
log2.data

array([( 2295.3452,   76.8985, -999.25  ),
       ( 2295.4976,   76.2669, -999.25  ),
       ( 2295.65  ,   77.0666, -999.25  ), ...,
       ( 3536.6432, -999.25  ,    2.6824),
       ( 3536.7956, -999.25  ,    2.6799),
       ( 3536.948 , -999.25  ,    2.6827)],
      dtype=[('DEPT', '<f8'), ('GR', '<f8'), ('RHOB', '<f8')])

In [7]:
np.set_printoptions(precision=4)

## Reading and assigning the logs:

**Important!** This code needs to be customized for each well. Unfortunately I still didn't find a way to integrate all of them with a general code. 

In [8]:
START = []
END = []
DEP = []
DEPT = []

N_files = len(las_files)

for i in range(N_files):              # Creating an empty array indexed with the depth
    
    globals()['log_%s' % i] = las.LASReader(las_files[i])
    np.set_printoptions(precision=4)
    
    globals()['DEPT_%s' % i] = globals()['log_%s' % i].data['DEPT']
    
    START_logs =  globals()['DEPT_%s' % i][0]
    START = np.append(START, START_logs)
    
    END_logs =  globals()['DEPT_%s' % i][-1]
    END = np.append(END, END_logs)
    
    DEPT_start = np.argmin(START)
    DEPT_end = np.argmax(END)
    
    sample_int = globals()['log_%s' % i].well.STEP.value
    N_samples = int((END[DEPT_end] - START[DEPT_start])/sample_int)+1
    
    Ini = START[DEPT_start] 
    
DEPT = np.append(DEPT, Ini)
    
for i in range(N_samples):   
    
    DE = Ini + sample_int
    DEP = np.append(DEP, DE)
    Ini = DE     
    
DEPT = np.append(DEPT, DEP)



counter = 0

count_d = []
count_r = []

for i in range(N_files):                  # counting the number of columns the same log appears in each file
        
    with open(las_files[i]) as f:
        contents = f.read()
        count = contents.count("Sonic")
        count_d = np.append(count_d, count)
        
    with open(las_files[i]) as f:
        contents = f.read()
        count = contents.count("Bulk")
        count_r = np.append(count_r, count)
          
            
            
# Analysis of the DT log


D = np.empty(N_samples+1,)          # Creating and empty array to receive the values
D[:] = np.nan
DT = D

count_d_i = np.where(count_d>0)

for i in range(np.asarray(count_d_i).size):
        
            
    if count_d[count_d_i[0][i]] == 1:                          # verifies if the same log is divided in different files
        
        
        globals()['log_S_%s' % i] = las.LASReader(las_files[count_d_i[0][i]])  # saves the logs which has DT log
        
        globals()['DEPT_S_%s' % i] = globals()['log_S_%s' % i].data['DEPT']   # Stores the depths of each file in different parameters
               
        
        x = 'DT_'
        y = i
        z = count_d_i[0][i]
            
        globals()['%s%s%s' % (x,y,z)] = globals()['log_S_%s' % i].data['DT']
        
        xv = 'valid_S_'
        yv = i
        zv = count_d_i[0][i]
        
        globals()['%s%s%s' % (xv,yv,zv)] = np.where(globals()['%s%s%s' % (x,y,z)] > 0)   # finding the set of valid values 

        globals()['idx_v_S_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][0]

        globals()['START_S_%s' % i] =  globals()['DEPT_S_%s' % i][globals()['idx_v_S_%s' % i]]  # finding the depth of the first valid value
        
        globals()['idx_S_start_%s' % i] = np.abs(globals()['START_S_%s' % i] - DEPT).argmin()   # index where the DT log starts in DEPT
        
        globals()['idx_v_E_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][-1] # finding the index of the last valid value 
        
        globals()['END_S_%s' % i] =  globals()['DEPT_S_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
        
        globals()['idx_S_end_%s' % i]  = np.abs(globals()['END_S_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT

        
        DT[(globals()['idx_S_start_%s' % i]):(globals()['idx_S_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['%s%s%s' % (xv,yv,zv)][0][0]:globals()['%s%s%s' % (xv,yv,zv)][0][-1]+1]
        
        
    if count_d[count_d_i[0][i]] > 1:   # verifies if the same log is divided in different columns
        
        globals()['log_S_%s' % i] = las.LASReader(las_files[count_d_i[0][i]])  # saves the logs which has DT log
        
        globals()['DEPT_S_%s' % i] = globals()['log_S_%s' % i].data['DEPT']   # Stores the depths of each file in different parameters
               
        
        x = 'DT_'
        y = i
        z = count_d_i[0][i]
                
        globals()['%s%s%s' % (x,y,z)] = globals()['log_S_%s' % i].data['DT']  # reading the first column
                
        xv = 'valid_S_'
        yv = i
        zv = count_d_i[0][i]
        
        globals()['%s%s%s' % (xv,yv,zv)] = np.where(globals()['%s%s%s' % (x,y,z)] > 0)
          
        globals()['idx_v_S_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][0]      # finding the index of the first valid value

        globals()['START_S_%s' % i] =  globals()['DEPT_S_%s' % (i)][globals()['idx_v_S_%s' % i]]  # finding the depth of the first valid value
        
        globals()['idx_S_start_%s' % i] = np.abs(globals()['START_S_%s' % i] - DEPT).argmin()   # index where the RHOB log starts in DEPT

        globals()['idx_v_E_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][-1] # finding the index of the last valid value
          
        globals()['END_S_%s' % i] =  globals()['DEPT_S_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
        
        globals()['idx_S_end_%s' % i]  = np.abs(globals()['END_S_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT
                  
        DT[(globals()['idx_S_start_%s' % i]):(globals()['idx_S_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['%s%s%s' % (xv,yv,zv)][0][0]:globals()['%s%s%s' % (xv,yv,zv)][0][-1]+1]
     
    
   
        
        for i in range(int(count_d[count_d_i[0][i]]) -1):  # Stores the logs divided in different columns in different parameters
                
            x = 'DT_'
            y = i
            z = count_d_i[0][i]
        
            globals()['DT_%s' % (i+1)] = globals()['log_S_%s' % i].data['DT_%s' % (i+1)]
            
                
            globals()['valid_s_%s' % (i+1)] = np.where(globals()['DT_%s' % (i+1)] > 0)
                    
            globals()['%s%s%s' % (x,y,z)][globals()['valid_s_%s' % (i+1)][:]] = globals()['DT_%s' % (i+1)][globals()['valid_s_%s' % (i+1)]]    

            globals()['idx_v_S_%s' % i] = globals()['valid_s_%s' % (i+1)][0][0]      # finding the index of the first valid value
            
            globals()['START_S_%s' % i] =  globals()['DEPT_S_%s' % (i)][globals()['idx_v_S_%s' % i]]  # finding the depth of the first valid value
                      
            globals()['idx_S_start_%s' % i] = np.abs(globals()['START_S_%s' % i] - DEPT).argmin()   # index where the RHOB log starts in DEPT
            
            globals()['idx_v_E_%s' % i] = globals()['valid_s_%s' % (i+1)][0][-1] # finding the index of the last valid value

            globals()['END_S_%s' % i] =  globals()['DEPT_S_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
            
            globals()['idx_S_end_%s' % i]  = np.abs(globals()['END_S_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT
        
                     
            DT[(globals()['idx_S_start_%s' % i]):(globals()['idx_S_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['valid_s_%s' % (i+1)][0][0]:globals()['valid_s_%s' % (i+1)][0][-1]+1]
               

null = np.where(np.nan_to_num(DT)<0)
DT[null] = np.nan




# Analysis of the RHOB log



R = np.empty(N_samples+1,)           # Creating an empty array to receive the values
R[:] = np.nan
RHOB = R

count_r_i = np.where(count_r>0) 

for i in range(np.asarray(count_r_i).size):
        
            
    if count_r[count_r_i[0][i]] == 1:                          # verifies if the same log is divided in different files
        
        
        globals()['log_B_%s' % i] = las.LASReader(las_files[count_r_i[0][i]])  # saves the logs which has DT log
        
        globals()['DEPT_B_%s' % i] = globals()['log_B_%s' % i].data['DEPT']   # Stores the depths of each file in different parameters
               
        
        x = 'RHOB_'
        y = i
        z = count_r_i[0][i]
            
        globals()['%s%s%s' % (x,y,z)] = globals()['log_B_%s' % i].data['RHOB']
        
        xv = 'valid_R_'
        yv = i
        zv = count_r_i[0][i]
        
        globals()['%s%s%s' % (xv,yv,zv)] = np.where(globals()['%s%s%s' % (x,y,z)] > 0)   # finding the set of valid values 

        globals()['idx_v_B_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][0]

        globals()['START_B_%s' % i] =  globals()['DEPT_B_%s' % i][globals()['idx_v_B_%s' % i]]  # finding the depth of the first valid value
        
        globals()['idx_B_start_%s' % i] = np.abs(globals()['START_B_%s' % i] - DEPT).argmin()   # index where the DT log starts in DEPT
        
        globals()['idx_v_E_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][-1] # finding the index of the last valid value 
        
        globals()['END_B_%s' % i] =  globals()['DEPT_B_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
        
        globals()['idx_B_end_%s' % i]  = np.abs(globals()['END_B_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT

        
        RHOB[(globals()['idx_B_start_%s' % i]):(globals()['idx_B_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['%s%s%s' % (xv,yv,zv)][0][0]:globals()['%s%s%s' % (xv,yv,zv)][0][-1]+1]
        
        
    if count_r[count_r_i[0][i]] > 1:   # verifies if the same log is divided in different columns
        
        globals()['log_B_%s' % i] = las.LASReader(las_files[count_r_i[0][i]])  # saves the logs which has DT log
        
        globals()['DEPT_B_%s' % i] = globals()['log_B_%s' % i].data['DEPT']   # Stores the depths of each file in different parameters
               
        
        x = 'RHOB_'
        y = i
        z = count_r_i[0][i]
                
        globals()['%s%s%s' % (x,y,z)] = globals()['log_B_%s' % i].data['RHOB']  # reading the first column
                
        xv = 'valid_B_'
        yv = i
        zv = count_r_i[0][i]
        
        globals()['%s%s%s' % (xv,yv,zv)] = np.where(globals()['%s%s%s' % (x,y,z)] > 0)
          
        globals()['idx_v_B_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][0]      # finding the index of the first valid value

        globals()['START_B_%s' % i] =  globals()['DEPT_B_%s' % (i)][globals()['idx_v_B_%s' % i]]  # finding the depth of the first valid value
        
        globals()['idx_B_start_%s' % i] = np.abs(globals()['START_B_%s' % i] - DEPT).argmin()   # index where the RHOB log starts in DEPT

        globals()['idx_v_E_%s' % i] = globals()['%s%s%s' % (xv,yv,zv)][0][-1] # finding the index of the last valid value
          
        globals()['END_B_%s' % i] =  globals()['DEPT_B_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
        
        globals()['idx_B_end_%s' % i]  = np.abs(globals()['END_B_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT
                  
        
        RHOB[(globals()['idx_B_start_%s' % i]):(globals()['idx_B_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['%s%s%s' % (xv,yv,zv)][0][0]:globals()['%s%s%s' % (xv,yv,zv)][0][-1]+1]
     
    
   
        
        for i in range(int(count_r[count_r_i[0][i]]) -1):  # Stores the logs divided in different columns in different parameters
                
            x = 'RHOB_'
            y = i
            z = count_r_i[0][i]
        
            globals()['RHOB_%s' % (i+1)] = globals()['log_B_%s' % i].data['RHOB_%s' % (i+1)]
            
                
            globals()['valid_b_%s' % (i+1)] = np.where(globals()['RHOB_%s' % (i+1)] > 0)
                    
            globals()['%s%s%s' % (x,y,z)][globals()['valid_b_%s' % (i+1)][:]] = globals()['RHOB_%s' % (i+1)][globals()['valid_b_%s' % (i+1)]]    

            globals()['idx_v_B_%s' % i] = globals()['valid_b_%s' % (i+1)][0][0]      # finding the index of the first valid value
            
            globals()['START_B_%s' % i] =  globals()['DEPT_B_%s' % (i)][globals()['idx_v_B_%s' % i]]  # finding the depth of the first valid value
                      
            globals()['idx_B_start_%s' % i] = np.abs(globals()['START_B_%s' % i] - DEPT).argmin()   # index where the RHOB log starts in DEPT
            
            globals()['idx_v_E_%s' % i] = globals()['valid_b_%s' % (i+1)][0][-1] # finding the index of the last valid value

            globals()['END_B_%s' % i] =  globals()['DEPT_B_%s' % i][globals()['idx_v_E_%s' % i]]   # finding the depth of the last valid value
            
            globals()['idx_B_end_%s' % i]  = np.abs(globals()['END_B_%s' % i] - DEPT).argmin()   # index where the DT log ends in DEPT
        
                     
            RHOB[(globals()['idx_B_start_%s' % i]):(globals()['idx_B_end_%s' % i])+1] = globals()['%s%s%s' % (x,y,z)][globals()['valid_b_%s' % (i+1)][0][0]:globals()['valid_b_%s' % (i+1)][0][-1]+1]
               



null = np.where(np.nan_to_num(RHOB)<0)
RHOB[null] = np.nan



In [9]:
DT

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [10]:
RHOB

array([    nan,     nan,     nan, ...,  2.6799,  2.6827,     nan])

In [11]:
DEPT

array([  570.482 ,   570.6344,   570.7868, ...,  3536.7956,  3536.948 ,
        3537.1004])

In [12]:
DEPT.size

19467

## Reading the start and end of the depth:

In [13]:
DEPT_start = DEPT[0]
DEPT_end = DEPT[-1]

In [14]:
print DEPT_start

570.482


In [15]:
print DEPT_end

3537.1004


## Exporting integrated logs to a txt file

In [16]:
Depth = np.array([DEPT])
Depth.T

array([[  570.482 ],
       [  570.6344],
       [  570.7868],
       ..., 
       [ 3536.7956],
       [ 3536.948 ],
       [ 3537.1004]])

In [17]:
DT = np.array([DT])
DT.T

array([[ nan],
       [ nan],
       [ nan],
       ..., 
       [ nan],
       [ nan],
       [ nan]])

In [18]:
RHOB = np.array([RHOB])
RHOB.T

array([[    nan],
       [    nan],
       [    nan],
       ..., 
       [ 2.6799],
       [ 2.6827],
       [    nan]])

In [19]:
logs_DT_RHOB_int = np.concatenate((Depth.T, DT.T, RHOB.T), axis=1)
logs_DT_RHOB_int

array([[  5.7048e+02,          nan,          nan],
       [  5.7063e+02,          nan,          nan],
       [  5.7079e+02,          nan,          nan],
       ..., 
       [  3.5368e+03,          nan,   2.6799e+00],
       [  3.5369e+03,          nan,   2.6827e+00],
       [  3.5371e+03,          nan,          nan]])

In [20]:
np.savetxt('logs_DT_RHOB_int.txt', (logs_DT_RHOB_int), fmt='%8.4f', delimiter='    ', newline='\n', header='', footer='', comments='# ') 

## Creating a .las file 

Now, to import the data into an integration software you need to create a new .las file with the header and the integrated data. Pay attention to change at the header the depth related to the start and end of the well and replace the null value by 'nan'. 

To see the header of well and create a new file .las, use the following command:

In [21]:
orig_stdout = sys.stdout
sys.stdout=open('out.las','w')

In [22]:
import numpy as np
with open('perfis/1RJS_0051__RJ_1RJS_0051__RJ_BHC_00003.las', 'r') as f:
    for line in f:
        if line.lstrip().startswith('~A'):
            break
        f = np.append(f, (line.rstrip()))
        print(line.rstrip())

In [23]:
# Insert the column RHOB to the file

In [24]:
sys.stdout=open('out.las','a')
print ('RHOB.                                                    :     3  Bulk density') 

In [25]:
# Insert the ASCII section

In [26]:
sys.stdout=open('out.las','a')
print(line.rstrip())

In [27]:
with open('logs_DT_RHOB_int.txt', 'r') as data:
    for line in data:
        if line.lstrip().startswith('~A'):
            break
        data = np.append(data, (line.rstrip()))
        print(line.rstrip())
data = (data, (line.rstrip()))

## Changing the value of some parameters:

In [28]:
import lasio

In [29]:
l = lasio.read('out.las')

In [30]:
l.well['STRT'] = lasio.HeaderItem('STRT', value=DEPT_start)

In [31]:
l.well['STOP'] = lasio.HeaderItem('STOP', value=DEPT_end)

In [33]:
l.well['NULL'] = lasio.HeaderItem('NULL', value='nan')

In [34]:
l.write('out_lasio.las', version=2)